export const PIECE_FEN_TYPES = {
  blackRook: "r",
  blackKnight: "n",
  blackBishop: "b",
  blackQueen: "q",
  blackKing: "k",
  blackPawn: "p",
  blackMoon: "m",
  blackGrave: "g",
  blackJester: "j",
  blackArchbishop: "a",
  blackChancellor: "c",
  blackRose: "o",
  whiteRook: "R",
  whiteKnight: "N",
  whiteBishop: "B",
  whiteQueen: "Q",
  whiteKing: "K",
  whitePawn: "P",
  whiteMoon: "M",
  whiteGrave: "G",
  whiteJester: "J",
  whiteArchbisho: "A",
  whiteChancellor: "C",
  whiteRose: "O",
};
